url: https://www.wijmentorschappen.nl/
baseurl:

# Site settings
title: Wij Mentorschappen
email: administratie@wijmentorschappen.nl
description: "Wij Mentorschappen, professionele positieve en persoonlijk mentorschap in de regio Gelderland en Overijssel"
logo: /img/logo.png
google_site_verification: uvxt7v2Tv1jVdJACQNj2Yqjpaycqvur1Ao7J1ilD1i0
lang: nl_NL

# Team names, titles and social links
people:
- name: Marieke Frohoff
  pic: 1
  phone: 06 49 200 334
  social:
    - title: linkedin
      url: https://www.linkedin.com/company/wij-mentorschappen
    - title: envelope
      url: mailto:marieke@wijmentorschappen.nl
- name: Annelies van der Have
  pic: 2
  phone: 06 49 488 812
  social:
    - title: linkedin
      url: https://www.linkedin.com/company/wij-mentorschappen
    - title: envelope
      url: mailto:annelies@wijmentorschappen.nl

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: linkedin
      url: https://www.linkedin.com/company/wij-mentorschappen
    - title: envelope
      url: mailto:info@wijmentorschappen.nl

# Build settings
markdown: kramdown
permalink: pretty/

plugins:
  - jekyll-seo-tag